server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_AUTH_HOST:localhost}:${DB_AUTH_PORT:5432}/${DB_AUTH_NAME:auth_db}
    username: ${DB_AUTH_USER:postgres}
    password: ${DB_AUTH_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-expiration: 900000
  refresh-expiration: 604800000