server:
  port: 4000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-public
          uri: http://${AUTH_SERVICE_HOST:localhost}:8081
          predicates:
            - Path=/api/v1/auth/register, /api/v1/auth/login, /api/v1/auth/refresh

        - id: auth-service-secured
          uri: http://${AUTH_SERVICE_HOST:localhost}:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - JwtAuthenticationFilter

        - id: hotel-service
          uri: http://${HOTEL_SERVICE_HOST:localhost}:8082
          predicates:
            - Path=/api/v1/hotels/**
          filters:
            - JwtAuthenticationFilter

        - id: booking-service
          uri: http://${BOOKING_SERVICE_HOST:localhost}:8083
          predicates:
            - Path=/api/v1/bookings/**
          filters:
            - JwtAuthenticationFilter

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}